sequenceDiagram

participant browser
participant server
activate browser
browser ->> server: GET https://studies.cs.helsinki.fi/exampleapp/spa
activate server
server -->> browser: Answer with the html document spa
deactivate server

activate browser 
browser ->> server : GET https://studies.cs.helsinki.fi/exampleapp/main.css
activate server
server -->> browser : Answer with the css document main.css
deactivate server

activate browser
browser ->> server : GET https://studies.cs.helsinki.fi/exampleapp/spa.js
activate server
server -->> browser : Browser loads the javascript file spa.js
deactivate server
Note right of browser: The browser starts executing the JavaScript code that fetches the JSON from the server

activate browser
browser ->> server : GET https://studies.cs.helsinki.fi/exampleapp/data.json
activate server 
server -->> browser : Browser download the json file which is processed by spa.js 
deactivate server
Note right of browser : The browser executes the function that renders the notes 


